messages/Cargo.toml
messages/src/lib.rs

- Fix Serde dependency to build with `no_std`
- Remove `ids_from_logical_ports`, since Ben was already planning to delete it
- Change the one remaining function that returned a `Vec` -> returning an iterator instead
- Drop `heapless` dependency, since we don't need it anymore
- Update tests
- Make `port_to_ids` public, since otherwise no one is using it (?)

Fixes for `no-std` build

---

messages/src/lib.rs
messages/src/message.rs
messages/src/mgmt/cmis.rs
messages/src/mgmt/mod.rs
messages/src/mgmt/sff8636.rs

- Adds support for declaring the management interface specification a transceiver conforms to. Currently supports SFF-8636 and CMIS, all others are unknown and unsupported.
- Adds better mechanisms for addressing the upper page of a transceiver memory map. It now supports an addressing scheme per-specification, which allows the older single-level paged memory of SFF-8636, and the newer page-and-bank-select mechanisms in CMIS. All values are checked against the spec, for both pages and banks, though that doesn't validate against the pages supported by the modules themselves.
- More tests for above.

Adds mechanisms to specify which management interface a transceiver uses

---

.github/buildomat/jobs/build-and-test.sh
messages/src/message.rs
messages/src/mgmt/cmis.rs
messages/src/mgmt/mod.rs
messages/src/mgmt/sff8636.rs

- Splits the `MemoryRegion` type into `Memory{Read,Write}`. These have different size limits.
- Adds the `MemoryPage` trait, implemented for the pages we currently support (SFF-8636 and CMIS). This describes the start / end of the page, as well as the maximum size of a read or write. These are used to construct the `Memory{Read,Write}` types for a specific page, where the offset / length of the access are validated.
- Beefs up tests.

Makes reads/writes of transceiver modules size-limited

---

LICENSE
controller/Cargo.toml
controller/src/bin/mock-sp.rs
controller/src/bin/xcvradm.rs
controller/src/lib.rs
messages/Cargo.toml
messages/src/lib.rs
messages/src/message.rs

- Adds a `Controller`, the main type which handles the network protocol between the host and SP. This spawns a tokio task for managing the actual UDP socket and for calling the user-supplied request-handler function. These communicate with the main controller via channels. The public API is basically a wrapper converting the data for each function into the right RPC message, and then passing that to the network task for sending and receiving the response.
- Adds a small CLI for running the controller manually. It currently does very little.
- Adds a dumb mock SP, which just responds to memory reads with zeros of the right size.

Adds basic host-side controller.

---

controller/Cargo.toml
controller/src/bin/xcvradm.rs
controller/src/lib.rs
messages/src/lib.rs
messages/src/message.rs

- Adds a `Config` type for specifying the configuration for a `Controller`. Currently provides knobs for retry duration/interval, local/remote IP addresses, and the IP interface. Plumbs these up to the `xcvradm` CLI tool.
- Adds a few convenience constructors to `PortMask` and `ModuleId`.
- Fixes bug where we send back a ProtocolError if the SP responds incorrectly to our outstanding request, but then just continues to try to send it. That leads to a silly ping-pong of error messages back and forth. Now we fail the request if we ever get back a ProtocolError, since it could never succeed.

Support for some configuration values

---

controller/src/lib.rs
messages/src/lib.rs
messages/src/message.rs

This adds a fine-grained `HwError` which provides details on SP -> FPGA -> transceiver errors.
It also introduces a few new member to the top-level `Error` enum.

Add hardware error type and bump to V2

---

Cargo.toml
controller/Cargo.toml
controller/src/bin/xcvradm.rs
controller/src/lib.rs
decode/Cargo.toml
decode/src/lib.rs
messages/Cargo.toml
messages/src/message.rs

- Adds Controller interface for setting the power mode of modules. Consumes via new CLI subcommand to `xcvradm`.
- Adds new crate `transceiver-decode` in the workspace for decoding data from transceiver memory maps. For now, includes the SFF-8024 style identifier and the vendor identity. Consumes via new `xcvradm identify` subcommand.
- Adds tests for the new decoding functionality.

Adds power-enable and decoding of vendor identity

---

controller/src/bin/xcvradm.rs
controller/src/lib.rs

- Adds the `Controller::reset` method for reseting some transceivers.
- Adds a `xcvradm reset` subcommand for consuming it.

Add a reset method

---

controller/Cargo.toml
controller/src/bin/xcvradm.rs
controller/src/lib.rs
decode/src/lib.rs
messages/src/lib.rs
messages/src/message.rs
messages/src/mgmt/cmis.rs
messages/src/mgmt/mod.rs
messages/src/mgmt/sff8636.rs

- Reworks `xcvradm` command to require the management interface it expects modules to use when reading / writing.
- Checks the management interface implied by the `Memory{Read,Write}` objects in the `Controller::{read,write}` methods.
- Adds errors for indicating that a module doesn't match the expected interface.
- Adds error variant indicating that a read / write is too big for the provided memory page based on its management interface. This is split off from the previous generic "invalid memory access" error, which didn't distinguish between something being out of bounds and something being in-bounds, but too large for a module (e.g., 4-byte writes for SFF-8636).
- Adds `xcvradm {read,write}-{lower,upper}` commands.
- Adds option to print read data in binary.

WIP: Adds support for writing to module memory

---

controller/Cargo.toml
controller/src/bin/xcvradm.rs
controller/src/lib.rs

Removes the async-trait for a request handler, and instead opts to take a send-half of a channel at construction. Rather than calling the request handler method directly, the controller now sends the request on that channel along with a oneshot for the reponse. It awaits the response on that oneshot; if it's Some(_), the message is serialized and sent back to the peer over the UDP socket; if it's None, the message is dropped. This approach reduces the complexity around ownership and generally allows more freedom to run the controller and handler in separate tasks.

Handle requests via a channel

---

controller/src/bin/xcvradm.rs
controller/src/lib.rs
messages/src/message.rs

Improves parsing of the list of transceivers on the command line, to allow a list of indices; all transceivers in a specific power mode (e.g., "off"); or all of a specific management interface (e.g., "cmis").

More flexible methods for addressing transceivers

---

controller/src/bin/xcvradm.rs
controller/src/lib.rs

The `IOLoop` previously took out of the optional outstanding message whenever we got a well-formed response, and _then_ checked if the message ID confirms that it's for the outstanding response. That was premature; we should only remove the outstanding message _after_ verifying the response we have is actually for that message.

Don't take an outstanding message unless we get its response

---

controller/src/bin/xcvradm.rs
controller/src/lib.rs

- Add a `port` to the `Config` and its builder, with a default of the protocol port 11112.
- Add CLI option for selecting this, defaulting to 0 for an arbitrary port.

Support a configurable source UDP port

---

controller/src/bin/xcvradm.rs
controller/src/lib.rs
decode/src/lib.rs
messages/src/lib.rs

This updates the various subcommands for managing a module's power state to handle the case where software override of power control is set. It keeps in place the existing, direct-control subcommands for setting the disposition of hardware signals, and changes the `power_mode` and `set_power_mode` functions to check for software override when operating.
Note that one goal here is always keep the hardware and software signals in sync. That is, if we request low-power mode, we set both the hardware `LPMode` pin and the right bit in the module memory map. The idea is that if one toggles the software-override, the power mode itself will not change.

Handles software control of power mode when setting module power

---

messages/src/lib.rs
messages/src/message.rs

This is part of the efforts to address https://github.com/oxidecomputer/hubris/issues/1069

Add a logical failure mask to HwError::I2cError

---

.github/buildomat/jobs/build-and-test.sh
Cargo.lock
controller/src/bin/xcvradm.rs
controller/src/lib.rs
messages/Cargo.toml
messages/src/lib.rs
messages/src/message.rs

- Add the `MacAddrs` message to the protocol, and `MacAddrs` type for representing the MAC range for various kinds of systems.
- Adds method to `Controller` and `xcvradm` subcommand for exercising.

Add message for collecting MAC addresses from SP

---

Cargo.lock
controller/Cargo.toml
controller/src/bin/xcvradm.rs
controller/src/lib.rs
decode/Cargo.toml
decode/src/lib.rs

- Derives `serde::Serialize`, `serde::Deserialize` and `schemars::JsonSchema` for `transceiver_control::PowerMode`.
- Derives `serde::Serialize`, `serde::Deserialize` and `schemars::JsonSchema` for `transceiver_decode::Vendor` and all required sub-types. This means serializing the OUI as a formatted string for now.
- Removes any parsing of the Date Code at all. It's either kept as an ASCII string (which the spec mandates it's supposed to be) or None, and printed that way. This avoids all the annoyance around parsing it into a type, which we really only care about at this point for printing anyway. This helps serialization, since it's just a string or nothing.

Add derivations of API-related traits

---

controller/src/lib.rs
messages/src/lib.rs
messages/src/message.rs
messages/src/mgmt/mod.rs

- Adds a minimum version of the network protocol. This is _committed_, in that we can never break backwards compatibility. There is also a CURRENT version, which can be different. This only serves as informational, to detect version mismatches and possibly warn about them.
- Adds tests that we can correctly [de]serialize _all_ current data used in the protocol. This should catch any changes that break the existing wire-encoding.
- Adds a sanity check for the new behavior in the IO loop for handling responses from the SP that do not match our version. We currently only _fail_ responses below our minimum committed version. We should never get responses to these, since all existing SP code will drop messages that don't match its own version, but this is a helpful sanity check. We also add …

Add committed minimum protocol version

---

controller/src/bin/xcvradm.rs
controller/src/controller.rs
controller/src/ioloop.rs

- Reads for some kinds of complex data are split by ID. That issues SFF reads first, before CMIS, simply because that's the sort order of the `Identifier` enum. After reading, data was pushed onto a vector, which may not respect the actual module order. For example, a CMIS module appearing before an SFF would result in seeing the SFF data as applying to the CMIS. Fixed by using a map from module index to the read data, which is collected into a vector at the end.
- Apply a few clippy nits

Fix out-of-order parsing of module data

---

controller/src/ioloop.rs
controller/src/lib.rs

Fixes #83.
With this, we now see:
```
BRM42220066 # dtrace -Zqn 'xcvr-ctl$target:::message-* { printf("%s\n", copyinstr(arg1)); }' -c '/tmp/xcvradm -i sidecar0 status'
Port Status
0 PRESENT | ENABLED | LOW_POWER_MODE | POWER_GOOD
1 PRESENT | ENABLED | LOW_POWER_MODE | POWER_GOOD
2 PRESENT | ENABLED | LOW_POWER_MODE | POWER_GOOD
3 ENABLED | LOW_POWER_MODE | INTERRUPT
4 PRESENT | ENABLED | LOW_POWER_MODE | POWER_GOOD
5 PRESENT | ENABLED | LOW_POWER_MODE | INTERRUPT | POWER_GOOD
6 PRESENT | ENABLED | LOW_POWER_MODE | INTERRUPT | POWER_GOOD
7 ENABLED | LOW_POWER_MODE | INTERRUPT
8 ENABLED | LOW_POWER_MODE | INTERRUPT
9 ENABLED | LOW_POWER_MODE | INTERRUPT
10 ENABLED | LOW_POWER_MODE | INTERRUPT
11 ENABLED | LOW_POWER_MODE | INTERRUPT
12 ENABLED | LOW_POWER_MODE | INTERRUPT
13 PRESENT | …
```

Add Header types to USDT probes

---

Cargo.lock
controller/Cargo.toml
controller/src/bin/xcvradm.rs
controller/src/controller.rs
controller/src/results.rs
dtrace/trace-packets.d
messages/Cargo.toml
messages/src/message.rs

This PR adds support for ports disabled by Hubris (see https://github.com/oxidecomputer/hubris/pull/1441)
- Adds a wider `StatusV2` type and message, which includes a bit for `DISABLED_BY_SP` (and 23 spare bits, just in case)
- Uses the `StatusV2` message in `xcvradm`
- Adds `HwError::DisabledBySp` and `HostRequest::ClearDisableLatch`
Before merging:
- Test on an actual Sidecar
- Bikeshedding about `StatusV2` (perhaps `ExtendedStatus`?  Or rename `Status` -> `HwStatus` and reclaim `Status`?), `HwError::DisabledBySp` and `HostRequest::ClearDisableLatch`, since I don't love any of those names
- Is this going to break anything that calls into `xcvradm`, since it changes types from `Status` -> `StatusV2` in a few places?

Add support for ports disabled by Hubris

---

messages/src/message.rs

Additions in support of https://github.com/oxidecomputer/hubris/issues/1562

Add more `HwError` variants

---

Cargo.toml
controller/src/bin/xcvradm.rs
controller/src/large_access.rs
controller/src/lib.rs
controller/src/results.rs
messages/src/module_id.rs

- Add the `LargeMemoryAccess` trait, which describes how to break a single large memory access, which may violate a transceiver's management spec, into smaller chunks. This is mostly ported directly from Dendrite, which already included this trait and tests for it.
- Use the large memory access trait to support _reads_ in `xcvradm` that are larger than the chunk-size limit.
- Add methods for appending a module result into another, where those results return an _array_ of items for each module. This is the case for the read operations, which return a byte array for each module.
- Add tests for the append operation

Break large memory accesses into chunks

---

messages/src/message.rs

We now support clock stretching when communicating with transceiver modules and that has lead to another potential error to be reported. See https://github.com/oxidecomputer/quartz/pull/210 for details.

Adds `HwError::I2cSclStretchTimeout`

---

Cargo.lock
controller/Cargo.toml
controller/src/bin/xcvradm.rs
controller/src/controller.rs
controller/src/lib.rs
controller/src/results.rs
decode/Cargo.toml
decode/src/datapath.rs
decode/src/ident.rs
decode/src/lib.rs
decode/src/monitors.rs
decode/src/utils.rs
messages/src/lib.rs
messages/src/message.rs
messages/src/mgmt/mod.rs

- Add methods for decoding SFF-8636 datapath. This is relatively simple, mostly including a bunch of flags indicating whether transmitters are enabled, LOS / LOL alarms are asserted, and the like.
- Add some macros for creating an enum from a bitfield. This has a few flavors, but generally lets us automatically create an enum where some defined subset of the bits is mapped to a variant name and a string `Display` representation for it. This includes support for specifying exactly which bits are expected to be set, as well as one or more catchall variants. This is mostly used for defining the giant enums for decoding SFF-8024 codes like the host electrical interface ID.
- Adds new enums for the key bits we need from a datapath: `ConnectorType`, `HostElectricalInterfaceId`, `MediaType`, …

Add support for decoding transceiver datapath state

---

controller/src/bin/xcvradm.rs
decode/src/datapath.rs

We're going to consume this in a downstream crate where there's already another type named `LaneStatus` in the API. This avoids the naming conflict, and is kind of helpful anyway to distinguish from an SFF-8636 datapath lane status.

Rename `LaneStatus` to `CmisLaneStatus`

---

decode/src/datapath.rs
decode/src/ident.rs

Renaming to avoid downstream OpenAPI collisions and for explicitness

Rename `Polarity` to `LanePolarity`

---

decode/src/ident.rs
decode/src/utils.rs

This changes to using the `fmt::Display` representation of all the various transceiver spec codes (compliance code, connector type, etc) for serializing them.

Use the display representation of transceiver codes for serialization
